### ISSUE TITLE
Repo not maintained?

### ISSUE THREAD

**Issue by timbze** [testcontainers/dind-drone-plugin#21]
It seems like this repo is not maintained?

I have forked and made my own docker image where the docker:dind image is updated and also implemented #19

If this repo is going to be maintained I would be more than happy to make a PR here. I'm not looking for more stuff to maintain 😄 

https://github.com/timbze/dind-drone-plugin
https://hub.docker.com/repository/docker/timbze/dind-drone-plugin/general

**Comment by timbze** [comment]
@rnorth

**Comment by rnorth** [comment]
Sorry - I'm on a bit of a hiatus, and this repo is not under the main project's area of focus. I'll look at #19 ASAP though - apologies.
